Changed the get_response method to get quicker responses from the app
plasticuproject/cleverbotfree pull request #10
Opened 2020-12-23 18:09 UTC by Devansh-bit

The sleeps in the get_response method make the response time very long. For overcoming this, the share button appearing in front of output line (Maybe added recently) has been used to detect the completion of the output. The button appears as soon as the app starts to send a response, but reaches full opacity value of 1 only on the completion of the output.

2020-12-23 21:36 UTC, plasticuproject requested changes
@Devansh-bit 
Nice find! I always hated the way I had that check for "completion", but just couldn't think of a good way to do it without all the waiting and comparing.

I noticed you removed the `StaleElementReferenceException` exception. I added that because for a while after x number of times the page would reload with an incremented page number. See Issue #3, as that was my fix for the issue. I'd like to have that back in there just in case.

Also don't forget to add `from selenium.common.exceptions import NoSuchElementException` to import the exception you added.

Also change `cb.browser.find_element_by_xpath` to `self.browser.find_element_by_xpath`.
If you add all that I'll test, merge, and upload the changes to pypi.

2020-12-24 20:01 UTC, Devansh-bit commented
I have added the changes you suggested in with the exception of the `StaleElementReferenceException`, with reference to Issue #3 .
The reason being that I tested the library for quite some time, 370 calls to be exact, and I was unable to replicate the error in Issue #3 . Even before this, I used a script very similar to this library and have made at least 1000 calls in a single session. I guess they removed the pagination you mentioned in the issue. If you insist, I can still add it back!

2020-12-25 05:11 UTC, plasticuproject approved these changes

2020-12-25 05:11 UTC, merged

2020-12-26 04:25 UTC, plasticuproject commented
Sorry, after some testing I found that using the share button was unreliable in production. When able to send multiple messages before a response was received (like with my discord bot implementation) the share button would stay on the page or not show up at all. Currently the module is a little slow, but works pretty reliably with multiple users sending asynchronous messages. I'm pretty bummed out as I was looking forward to the increased speed, but ultimately reliability across applications is more important.